Repository hassio-addons/addon-adguard-home, pull requests merged in 2021-04, with the labels that each got.

#149 Upgrades add-on base image to v9.2.0
  adguard/Dockerfile
  adguard/build.json
Labels: dependencies

#155 ⬆️ Upgrades AdGuard Home to v0.106.0
  adguard/Dockerfile
Labels: dependencies, minor

#157 Apply updated repository structure & CI workflow
  .editorconfig
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/SECURITY.md
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/pr-labels.yaml
Labels: ci

#158 ⬆️ Upgrades AdGuard Home to v0.106.1
  adguard/Dockerfile
Labels: dependencies
