Repository hassio-addons/addon-adguard-home, pull requests merged in 2021-12, with the labels that each got.

#280 :rocket: Update CI to latest version
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#283 ⬆️ Upgrades add-on base image to 11.0.0
  adguard/Dockerfile
  adguard/build.yaml
Labels: dependencies

#281 🔨 Update backup_exclude for rotated query logs
  adguard/config.yaml
Labels: enhancement

#253 Bind on all interfaces
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: enhancement

#284 ⬆️ Upgrades AdGuard Home to v0.107.0
  adguard/Dockerfile
Labels: minor, dependencies

#288 ⬆️ Upgrades AdGuard Home to v0.107.2
  adguard/Dockerfile
Labels: dependencies
