Repository hassio-addons/addon-adguard-home, pull requests merged in 2021-05, with the labels that each got.

#167 ⬆️ Upgrades AdGuard Home to v0.106.3
  adguard/Dockerfile
Labels: dependencies

#168 Add support for multiple bind interfaces
  adguard/rootfs/etc/adguard/AdGuardHome.yaml
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: enhancement

#169 Handle AdGuard config schema upgrades for bind hosts
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#170 Clean out previous bind values before adding new
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#171 Fix multiple address on a single interface
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#172 Fix interfaces with correctly configured multiple addresses
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#179 Fix binding to local link addresses
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#180 Ensure compared variable is bound
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#186 Use double parentheses for arithmetic expression
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#187 Ensure AdGuard can do migration from < 7 config schemas
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#189 Ensure AdGuard can do migration from config without schema version
  adguard/rootfs/etc/cont-init.d/adguard.sh
Labels: bugfix

#199 🔨 Switch yq to Alpine Package
  adguard/Dockerfile
  adguard/bin/yq_aarch64
  adguard/bin/yq_amd64
  adguard/bin/yq_armhf
  adguard/bin/yq_armv7
  adguard/bin/yq_i386
Labels: dependencies, refactor

#205 ⬆️ Upgrades add-on base image to v9.2.1
  adguard/Dockerfile
  adguard/build.json
Labels: dependencies
