Repository hassio-addons/addon-adguard-home, pull requests merged in 2022-07, with the labels that each got.

#327 ⬆️ Upgrades add-on base image to 12.2.1
  adguard/Dockerfile
  adguard/build.yaml
  adguard/rootfs/etc/services.d/nginx/finish
Labels: dependencies

#326 ⬆️ Upgrades AdGuard Home to v0.107.8
  adguard/Dockerfile
Labels: dependencies

#330 ⬆️ Upgrades yq to 4.25.1-r2
  adguard/Dockerfile
Labels: dependencies

#329 ⬆️ Upgrades add-on base image to 12.2.2
  adguard/Dockerfile
  adguard/build.yaml
Labels: dependencies

#328 Add Health Checks
  adguard/Dockerfile
Labels: new-feature

#323 📚 Update installation doc with proper link
  adguard/DOCS.md
Labels: documentation
