Repository hassio-addons/addon-adguard-home, pull requests merged in 2022-06, with the labels that each got.

#321 ⬆️ Upgrades add-on base image to 12.0.0
  adguard/Dockerfile
  adguard/build.yaml
  adguard/rootfs/etc/cont-init.d/adguard.sh
  adguard/rootfs/etc/cont-init.d/discovery.sh
  adguard/rootfs/etc/cont-init.d/nginx.sh
  adguard/rootfs/etc/services.d/adguard/run
  adguard/rootfs/etc/services.d/nginx/finish
  adguard/rootfs/etc/services.d/nginx/run
Labels: minor, dependencies

#320 ⬆️ Upgrades AdGuard Home to v0.107.7
  adguard/Dockerfile
Labels: dependencies

#322 :books: Use new My Home Assistant link format
  adguard/DOCS.md
Labels: documentation
